backend/campingapp/camping/urls.py
from django.urls import path
from campingapp.camping.views import detail, post, update, delete

app_name = "camping"
urlpatterns = [
    path("<int:camping_info_id>/", detail, name="detail"),
    path("update/<int:camping_info_id>/", update, name="update"),
    path("delete/<int:camping_info_id>/", delete, name="delete"),
    path("post/", post, name="post"),
]

backend/configuration/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from campingapp.camping.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("camping/", include("campingapp.camping.urls")),
    path("auth/", include("campingapp.auth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/campingapp/camping/forms.py
from django import forms
from campingapp.models import CampingInfo


# title = models.CharField(max_length=20, null=False)
# review = models.CharField(max_length=200, null=False)
# facility_star = models.IntegerField()
# visited_at = models.DateField()
# user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
# total_star = models.FloatField()


class PostForm(forms.ModelForm):
    visited_at = forms.DateField(
        required=True, widget=forms.DateInput(attrs={"type": "date"})
    )

    title = forms.CharField(
        max_length=20,
        required=True,
        label="캠핑장이름",
        widget=forms.TextInput(
            attrs={"class": "form-control mt-2", "type": "text", "placeholder": "캠핑장이름"}
        ),
    )

    review = forms.CharField(
        max_length=100,
        required=True,
        label="캠핑장리뷰",
        widget=forms.TextInput(
            attrs={
                "class": "form-control mt-2",
                "type": "text",
                "placeholder": "캠핑장리뷰",
            }
        ),
    )

    facility_star = forms.IntegerField(
        required=True,
        label="시설평점",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "시설평점",}),
    )

    visited_at = forms.DateField(
        required=True,
        label="방문날짜",
        widget=forms.TextInput(
            attrs={"class": "form-control mt-2", "type": "date", "placeholder": "방문날짜",}
        ),
    )

    image = forms.ImageField(
        required=True,
        label="썸네일: ",
        widget=forms.FileInput(
            attrs={"class": "mt-2", "type": "file", "name": "image"},
        ),
    )

    CHOICES = [("T", "접지"), ("F", "접지x"), ("ETC", "모름")]
    ground_on = forms.CharField(
        required=True,
        label="접지가 되어있니?",
        widget=forms.Select(
            choices=CHOICES,
            attrs={"class": "btn btn-info dropdown-toggle btn-block mt-1"},
        ),
    )

    CHOICES = [("T", "가능"), ("F", "불가"), ("ETC", "모름")]
    with_animal = forms.CharField(
        required=True,
        label="반려동물 가능?",
        widget=forms.Select(
            choices=CHOICES,
            attrs={"class": "btn btn-info dropdown-toggle btn-block mt-1"},
        ),
    )

    CHOICES = [
        ("forest", "숲쀼"),
        ("ocean", "오션뷰~~~"),
        ("lake", "호수뷰!"),
        ("simple", "시설맛집!"),
        ("shit", "똥뷰!"),
        ("etc", "그외!"),
    ]
    kind_of_view = forms.CharField(
        required=True,
        label="쀼는 어때?",
        widget=forms.Select(
            choices=CHOICES,
            attrs={"class": "btn btn-info dropdown-toggle btn-block mt-1"},
        ),
    )

    CHOICES = [
        ("roud", "시끄러움"),
        ("quiet", "조용조용"),
        ("normal", "괜찮음"),
    ]
    kind_of_camper = forms.CharField(
        required=True,
        label="캠퍼는 조용해?",
        widget=forms.Select(
            choices=CHOICES,
            attrs={"class": "btn btn-info dropdown-toggle btn-block mt-1"},
        ),
    )

    CHOICES = [
        ("T", "가능"),
        ("F", "불가능"),
        ("etc", "모름"),
    ]
    can_fire = forms.CharField(
        required=True,
        label="불멍하고싶다",
        widget=forms.Select(
            choices=CHOICES,
            attrs={"class": "btn btn-info dropdown-toggle btn-block mt-1"},
        ),
    )

    atmosphere_star = forms.IntegerField(
        required=True,
        label="분위기 평점",
        min_value=1,
        max_value=5,
        widget=forms.TextInput(attrs={"class": "form-control", "type": "number"}),
    )

    class Meta:
        model = CampingInfo
        fields = (
            "title",
            "review",
            "visited_at",
            "ground_on",
            "with_animal",
            "kind_of_view",
            "kind_of_camper",
            "can_fire",
            "atmosphere_star",
            "facility_star",
            "image",
        )

backend/campingapp/camping/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from campingapp.camping.forms import PostForm
from campingapp.models import CampingInfo, Photo


def index(request):
    # 캠핑 모델을 불러와야함
    context = {"campinginfo": CampingInfo.objects.all().order_by("-created_at")}
    return render(request, "index.html", context)


def detail(request, camping_info_id):
    camping = CampingInfo.objects.filter(id=camping_info_id).first()

    context = {"camping": camping}

    return render(request, "camping/detail.html", context)


def post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            camping_info = form.save(commit=False)
            camping_info.total_star = (
                camping_info.facility_star * 0.5 + camping_info.atmosphere_star * 0.5
            )

            camping_info.image = request.FILES.get("image")
            camping_info.user = request.user
            camping_info.save()

            # for img in request.FILES.getlist("imgs"):
            #     photo = Photo()
            #     photo.camping_info = camping_info
            #     photo.image = img
            #     photo.save()

            return redirect("index")
    else:
        # GET 요청
        form = PostForm()

    context = {"form": form}
    return render(request, "camping/post.html", context)


def update(request, camping_info_id):
    camping_info = get_object_or_404(CampingInfo, id=camping_info_id)
    if request.user.id != camping_info.user_id:
        messages.error(request, "수정 권한 없음 ㅅㄱ")
        # return redirect("index")

    if request.method == "POST":
        form = PostForm(request.POST, instance=camping_info)
        if form.is_valid():
            camping = form.save(commit=False)
            camping.image = request.FILES.get("image")
            form.save()

            return redirect("camping:detail", camping_info_id=camping_info.id)
    else:
        form = PostForm(instance=camping_info)
    context = {"form": form, "camping": camping_info}
    return render(request, "camping/update.html", context)


def delete(request, camping_info_id):
    camping_info = get_object_or_404(CampingInfo, id=camping_info_id)
    if request.user.id != camping_info.user_id:
        messages.error(request, "삭제권한없음 ㅅㄱ")
        return redirect("index")

    camping_info.delete()
    return redirect("index")

backend/templates/camping/detail.html
{% extends 'layout.html' %}
{% load  camping_filter %}
{% load static %}

{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
    detail
{% endblock %}

{% block content %}
<div class="image-box mt-2">
    <img src="{{ camping.image.url }}" alt="" class="image-thumbnail">
</div>

<div class="mt-5 p-3">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">정보</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">캠핑장</th>
            <td>{{ camping.title }}</td>
        </tr>
        <tr>
            <th scope="row">접지여부</th>
            <td>{{ camping.ground_on | ground_on }}</td>
        </tr>
        <tr>
            <th scope="row">반려동물가능?</th>
            <td>{{ camping.with_animal | with_animal }}</td>
        </tr>
        <tr>
            <th scope="row">뷰 종류는</th>
            <td>{{ camping.kind_of_view | kind_of_view }}</td>
        </tr>
        <tr>
            <th scope="row">캠퍼는 조용하니?</th>
            <td>{{ camping.kind_of_camper | kind_of_camper }}</td>
        </tr>
        <tr>
            <th scope="row">불멍하고싶니?</th>
            <td>{{ camping.can_fire | can_fire }}</td>
        </tr>
        <tr>
            <th scope="row">전반적인분위기는? [1-5]</th>
            <td>{{ camping.atmosphere_star }}</td>
        </tr>
        <tr>
            <th scope="row">시설평점 [1-5]</th>
            <td>{{ camping.facility_star }}</td>
        </tr>
        <tr>
            <th scope="row">전체평점</th>
            <td>{{ camping.total_star }}</td>
        </tr>
        </tbody>
    </table>

    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">리뷰</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">{{ camping.review }}</th>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

backend/templates/camping/post.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}POST{% endblock %}

{% block head %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <h2>post form</h2>
            <p class="lead">여기에 캠핑장 정보를 입력 등록정보는 계속해서 업데이트 될 예정</p>
        </div>

        <form action="{% url 'camping:post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">

                <div class="col-md-12 order-md-1">
                    <h4 class="mb-3">캠핑장 정보</h4>
                    <form class="needs-validation" novalidate>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                {{ form.title.label }}
                                {{ form.title }}
                            </div>

                            <div class="col-md-6 mb-3">
                                {{ form.visited_at.label }}
                                {{ form.visited_at }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-3 col-md-12">
                                {{ form.review.label }}
                                {{ form.review }}
                            </div>


                        </div>
                        <div class="row">
                        <div class="col-md-6">
                                {{ form.facility_star.label }}
                                {{ form.facility_star }}
                            </div>

                            <div class="col-md-6">
                                {{ form.atmosphere_star.label }}
                                {{ form.atmosphere_star }}
                            </div>
                        </div>

                        <div class="row mt-4">

                            <div class="col-md-4">
                                {{ form.ground_on.label }}
                                {{ form.ground_on }}
                            </div>

                            <div class="col-md-4">
                                {{ form.with_animal.label }}
                                {{ form.with_animal }}
                            </div>

                            <div class="col-md-4">
                                {{ form.kind_of_camper.label }}
                                {{ form.kind_of_camper }}
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-md-6">
                                {{ form.kind_of_view.label }}
                                {{ form.kind_of_view }}
                            </div>

                            <div class="col-md-6">
                                {{ form.can_fire.label }}
                                {{ form.can_fire }}
                            </div>
                        </div>




                        <div class="custom-file mt-4">
                            {{ form.image.label }}
                            {{ form.image }}
{#                            <label class="custom-file-label" for="customFile">Choose file</label>#}
                        </div>


                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">등록</button>
                    </form>
                </div>
            </div>
        </form>


    </div>
{% endblock %}


{##}
{#    {{ form.title }}#}
{#    {{ form.review }}#}
{#    {{ form.visited_at }}#}
{#    {{ form.facility_star }}#}
{##}
{#    <div class="custom-file">#}
{#        <input type="file" class="custom-file-input" id="customFile" name="imgs" multiple/>#}
{#        <label class="custom-file-label" for="customFile">Choose file</label>#}
{#    </div>#}
{#    <button type="submit" class="btn btn-primary btn-lg btn-block mt-4 mb-4 py-2">#}
{#        확인#}
{#    </button>#}

backend/templates/camping/update.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}POST{% endblock %}

{% block head %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <h2>post form</h2>
            <p class="lead">여기에 캠핑장 정보를 입력 등록정보는 계속해서 업데이트 될 예정</p>
        </div>

        <form action="{% url 'camping:update' camping_info_id=camping.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">

                <div class="col-md-12 order-md-1">
                    <h4 class="mb-3">캠핑장 정보</h4>
                    <form class="needs-validation" novalidate>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                {{ form.title.label }}
                                {{ form.title }}
                            </div>

                            <div class="col-md-6 mb-3">
                                {{ form.visited_at.label }}
                                {{ form.visited_at }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-3 col-md-8">
                                {{ form.review.label }}
                                {{ form.review }}
                            </div>

                            <div class="col-md-4">
                                {{ form.facility_star.label }}
                                {{ form.facility_star }}
                            </div>
                        </div>

{#                        <div class="input-group mb-3">#}
{#                            <div class="input-group-prepend">#}
{#                                <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>#}
{#                            </div>#}
{#                            <div class="custom-file">#}
{#                                <input type="file" class="custom-file-input" id="inputGroupFile01"#}
{#                                       aria-describedby="inputGroupFileAddon01" name="imgs" multiple>#}
{#                                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>#}
{#                            </div>#}
{#                        </div>#}
                        <input type="file" name="imgs" multiple>

                        <hr class="mb-4">




                            <div class="row">
                                <button class="btn btn-primary  col-md-6" type="submit">수정</button>

                                <button class="btn btn-danger  col-md-6" type="button" onclick="location.href='{% url "camping:delete" camping_info_id=camping.id%}'">삭제</button>

                            </div>






                    </form>
                </div>
            </div>
        </form>


    </div>
{% endblock %}


{##}
{#    {{ form.title }}#}
{#    {{ form.review }}#}
{#    {{ form.visited_at }}#}
{#    {{ form.facility_star }}#}
{##}
{#    <div class="custom-file">#}
{#        <input type="file" class="custom-file-input" id="customFile" name="imgs" multiple/>#}
{#        <label class="custom-file-label" for="customFile">Choose file</label>#}
{#    </div>#}
{#    <button type="submit" class="btn btn-primary btn-lg btn-block mt-4 mb-4 py-2">#}
{#        확인#}
{#    </button>#}

backend/templates/camping/updateasdf.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}POST{% endblock %}

{% block head %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <h2>post form</h2>
            <p class="lead">여기에 캠핑장 정보를 입력 등록정보는 계속해서 업데이트 될 예정</p>
        </div>

        <form action="{% url 'camping:update' camping_info_id=camping.id %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">

                <div class="col-md-12 order-md-1">
                    <h4 class="mb-3">캠핑장 정보</h4>
                    <form class="needs-validation" novalidate>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                {{ form.title.label }}
                                {{ form.title }}
                            </div>

                            <div class="col-md-6 mb-3">
                                {{ form.visited_at.label }}
                                {{ form.visited_at }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-3 col-md-8">
                                {{ form.review.label }}
                                {{ form.review }}
                            </div>

                            <div class="col-md-4">
                                {{ form.facility_star.label }}
                                {{ form.facility_star }}
                            </div>
                        </div>


                        <div class="custom-file mt-4">
                            {{ form.image.label }}
                            {{ form.image }}
{#                            <label class="custom-file-label" for="customFile">Choose file</label>#}
                        </div>

                        <hr class="mb-4">


                        <div class="row">
                            <button class="btn btn-primary  col-md-6" type="submit">수정</button>

                            <button class="btn btn-danger  col-md-6" type="button"
                                    onclick="location.href='{% url "camping:delete" camping_info_id=camping.id %}'">삭제
                            </button>

                        </div>


                    </form>
                </div>
            </div>
        </form>


    </div>
{% endblock %}


{##}
{#    {{ form.title }}#}
{#    {{ form.review }}#}
{#    {{ form.visited_at }}#}
{#    {{ form.facility_star }}#}
{##}
{#    <div class="custom-file">#}
{#        <input type="file" class="custom-file-input" id="customFile" name="imgs" multiple/>#}
{#        <label class="custom-file-label" for="customFile">Choose file</label>#}
{#    </div>#}
{#    <button type="submit" class="btn btn-primary btn-lg btn-block mt-4 mb-4 py-2">#}
{#        확인#}
{#    </button>#}