backend/campingapp/auth/urls.py
from django.urls import path
from campingapp.auth.views import signin, signup, signout


app_name = "auth"

urlpatterns = [
    path("signin", signin, name="signin"),
    path("signup", signup, name="signup"),
    path("signout", signout, name="signout"),
]

backend/campingapp/camping/urls.py
from django.urls import path
from campingapp.camping.views import detail, post, update, delete

app_name = "camping"
urlpatterns = [
    path("<int:camping_info_id>/", detail, name="detail"),
    path("update/<int:camping_info_id>/", update, name="update"),
    path("delete/<int:camping_info_id>/", delete, name="delete"),
    path("post/", post, name="post"),
]

backend/configuration/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from campingapp.camping.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("camping/", include("campingapp.camping.urls")),
    path("auth/", include("campingapp.auth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/templates/_errors.html
{% for message in messages %}
    {{ message }}
{% endfor %}

backend/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} camping {% endblock %}

{% block head %}
    {{ block.super }}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <link href="{% static 'css/camping.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1>캠핑장 방문 기록 써보자</h1>
                <p class="lead text-muted">아거는 내가 처음 만드는 캠핑장 방문 기록이며, 전기차 충전 가능 여부와 다른 앱에서 불편하다고 생각했던 것들 기록해놓는 서비스임
                    따라서 기능적인 부분은 매우 부족함 ==> 이걸 토대로 계속 만들어나갈거임 현재는 SPA서비스가 아니나 추후에 SPA로 업데이트 될 예정</p>
                <p>
                    <a href="{% url 'camping:post' %}" class="btn btn-primary my-2">리뷰 등록</a>
                    {#                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>#}
                </p>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row">
                    {% for camping in campinginfo %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                                     xmlns="http://www.w3.org/2000/svg" role="img"
                                     aria-label="Placeholder: Thumbnail"
                                     preserveAspectRatio="xMidYMid slice" focusable="false">
                                    <rect width="100%" height="100%" fill="#EBE9E8"/>
                                    <image href="{{ camping.image.url }}" width="100%" height="225"/>

                                </svg>
                                <div class="card-body">
                                    <p class="card-text">{{ camping.title }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-outline-secondary"
                                                    onclick="location.href='{% url "camping:detail" camping_info_id=camping.id %}'">
                                                View
                                            </button>
                                            {% if request.user.id == camping.user_id %}
                                            <button type="button" class="btn btn-sm btn-outline-secondary"
                                                    onclick="location.href='{% url "camping:update" camping_info_id=camping.id %}'">
                                                Edit
                                            </button>
                                            {% endif %}
                                        </div>
                                        <small class="text-muted">{{ camping.user.username }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>
            </div>
        </div>

    </main>

{% endblock %}

backend/templates/layout.html
<!doctype html>
<html lang="ko">
<head>
{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    {# bootstrap css #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
{% endblock %}
</head>
<body>
{% include 'navbar.html' %}
{% block content %}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
</body>
</html>

backend/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>


      {% if user.is_authenticated %}
          <a class="nav-link text-muted" href="{% url 'auth:signout' %}">Signout</a>
      {% else %}
          <a class="nav-link text-muted" href="{% url 'auth:signin' %}">Signin</a>
          <a class="nav-link text-muted" href="{% url 'auth:signup' %}">Signup</a>
      {% endif %}


      {% if user.is_authenticated %}
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{{ user.username }}</button>
      {% endif %}


  </div>
</nav>